version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  order_producer:
    build: ./order_producer
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - broker
      - zookeeper
      - db
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.orders
      REDIS_URL: redis://redis:6379
  order_consumer:
    build: ./order_consumer
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      - broker
      - zookeeper
      - db
    env_file:
      - ./order_consumer/.env.dev
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.orders
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:postgres@db:5432/orders
      APP_SETTINGS: config:DevelopmentConfig
  order_processor:
    build: ./order_processor
    ports:
      - "5003:8080"
    volumes:
      - .:/processor
    depends_on:
      - broker
      - zookeeper
      - db
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.orders
      REDIS_URL: redis://redis:6379
  #  order_producer:
  #    build: ./order_producer
  #    environment:
  #      KAFKA_BROKER_URL: broker:9092
  #      TRANSACTIONS_TOPIC: queueing.orders
  #  order_receiver:
  #    build: ./order_receiver
  #    ports:
  #      - "5000:5000"
  #    depends_on:
  #      - redis
  #      - db
  #      - broker
  #      - zookeeper
  #    environment:
  #      KAFKA_BROKER_URL: broker:9092
  #      TRANSACTIONS_TOPIC: queueing.orders
  #      REDIS_URL: redis://redis:6379
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#volumes:
#  postgres_data: